project:
  type: website
  output-dir: docs

website:
  repo-url: "https://github.com/margofreed/margofreed.github.io"
  repo-actions: [edit, issue]
  
  title: "Busy Balanced Life"
  navbar:
    left:
      - href: index.qmd
        text: Home
        icon: house
        
      - href: about.qmd
        text: About Me
        icon: file-person
      
      - href: mealprep.qmd
        text: Meal Prep
        icon: basket2-fill
    
    right:
      - href: "https://margofreed.github.io/"
        icon: github
        
format:
  html:
    theme: united
    css: styles.css
    toc: true



