project:
  type: website
  output-dir: docs

website:
  title: "Busy Balanced Life"
  site-url: "https://margofreed.github.io"
  repo-url: "https://github.com/margofreed/margofreed.github.io"
  repo-actions: [edit, issue]
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    background: "#AD4132"
    left:
      - href: index.qmd
        text: Home
        icon: house
      - href: about.qmd
        text: About Me
        icon: file-person
      - href: web6_practice.qmd
        text: Extras
        icon: emoji-laughing
      - text: Meal Preps
        icon: basket2-fill
        menu:
        - text: Breakfast Options
          href: pages/breakfast.qmd
        - text: Lunches
          href: mealprep.qmd
          

        
    right:
      - href: "https://github.com/margofreed/margofreed.github.io"
        icon: github
        
format:
  html:
    theme: united
    css: styles.css
    toc: true
    number-sections: true
    backgroundcolor: "#F8F9FA" 
    monobackgroundcolor: "#E8D496" 
    title-block-banner: "#AD4132" 
    title-block-banner-color: "#CFDAD3" 
    fontcolor: "#AD4132" 
    linkcolor: "#0E11E2" # hyperlink blue


